Line 58 throws an exception at compile time
I couldn't fix it, but the reason for it not to compile is this exception being thrown:

vyper.exceptions.InvalidLiteralException: line 58: Assignment to None is not allowed, use a default value or built-in `clear()`.
        self.funders[i] = None